### ISSUE TITLE
when installed 

### ISSUE THREAD

**Issue by dutchronnie** [markusressel/ESPHome-Smart-Scale#1]
After i made the card, i get an error: Entity is not available: input_number.weight_markus

Is there some code missing?

**Comment by markusressel** [comment]
Hey @dutchronnie !

It's just an example, `input_number.weight_markus` is (obviously) an input number that holds my personal weight. Just remove it if you don't want to have this. Otherwise you need to create an input_number entity in your home assistant instance.

**Comment by dutchronnie** [comment]
Thanks Markus,

I made an input number, and now it is working.
Stupid i didn't see

**Comment by markusressel** [comment]
No worries, glad it's working now.
Have fun!
