### ISSUE TITLE
update_interval in 'smart_scale_hx711_value' template causing extra transmit

### ISSUE THREAD

**Issue by sbrk-r** [markusressel/ESPHome-Smart-Scale#10]
In the logger I'm seeing duplicate transmissions of the mass (maybe more obvious when you slow everything down from 0.2s to 5 or 10s). 

The result of 'smart_scale_hx711_value' template will automatically transmit when data is pushed to it by 'sensor.template.publish' in the 'platform: hx711' section, so having "update_interval: 0.2s" is causing a second transmission, it seems. 

Changing it to 'update_interval: never' resolves the issue for me, I now only see a single transmission in the logger.

Also, sort of related, but the 'platform: hx711' has 'unit_of_measurement: kg' and 3 decimals set, but the 'sensor.template.publish' section is actually pushing the raw (err quantized) ADC value, so it gives you the bogus:
"Sending state 321380.00000 kg with 3 decimals of accuracy" in debug log. (of course it is an integer, in ADC steps, not kg). 

I'm really new to ESPHome so maybe I'm misunderstanding, the logger isn't super clear and doesn't really differentiate between "Sending" to HA, or "Sending" to an internal template.

**Comment by markusressel** [comment]
Thx for the report, this also might explain the random spikes we saw in #2 🤔 When I get time I will try to investigate this.

**Comment by markusressel** [comment]
I have checked both isses and you are correct. Fix is merged.
Let me know if you find anything else :nerd_face:
