### ISSUE TITLE
Pinout of Diagram doesn't match the code

### ISSUE THREAD

**Issue by wBrhy2** [markusressel/ESPHome-Smart-Scale#15]
D0 and D1 in the code should be replaced by 2 (D4) and 14 (D5) as per the diagram or GPIO16 and GPIO5 if still using D1 and D0.

**Comment by markusressel** [comment]
The diagram is just an example. It doesn't even show an ESP based board. The pinout can be different between boards so there is no single right answer. I didnt create my own diagram because of laziness, but I would love to accept an updated diagram for an actual esp board via PR.

**Comment by wBrhy2** [comment]
I get that, it's just that D1 and D0 are not (or at least no longer) supported as declared pins by ESPhome so it would be good to write GPIO16 and comment #pin D1 and GPIO5 and comment #pin D0. ESPhome is meant to be pretty beginner friendly, which means there are probably people who don't know that the pin numbers don't correspond to the GPIO numbers (I even forgot when I was configuring my scale despite having written dozens of C++ arduino and ESP codes)

**Comment by markusressel** [comment]
Sure thing!
Can you post a link to the documentation about this change?
Like already mentioned, feel free to create a PR for this change with a brief explanation :smile:

**Comment by wBrhy2** [comment]
Lol sure, and I'll make more of the code with symbolic links so it's more customizable for people. I guess it's about time I learn to do PRs!

**Comment by markusressel** [comment]
Since there hasn't been any activity here, and this doesn't seem to be an issue for people, I am going to close this.
Feel free to engage if desired.
