### ISSUE TITLE
Tare trigger from GPIO input ?

### ISSUE THREAD

**Issue by cayote64** [markusressel/ESPHome-Smart-Scale#19]
I'm wondering if anyone can help.

I have used this with an ESP8266 board in an outside hedgehog box. It weighs the hogs as they are feeding. Everything works, however the zero reading drifts massively being outside. I have tried a previous auto tare which keeps the reading at 0g throughout the day, but the weight is quite a distance out once the temperatures drop on the night.

Can anyone include some code so that I can use a spare GPIO pin on the board so as the hog enters the box, the scales zero themselves before it reaches the main compartment ?

Current code is:

globals:

id: constant_weight
type: float
`captive_portal:

sensor:

platform: hx711
id: weight
name: "HX711 Value2"
dout_pin: GPIO14
clk_pin: GPIO12
gain: 128
update_interval: 5s
unit_of_measurement: g
filters:
calibrate_linear:
- 68604 -> 0
- 626959 -> 2030
on_value:
- if:
condition:
- lambda: |-
static float last = 0.0;
float diff = x - last;
last = x;
return x < 50.0 && diff < 1.0 && diff > - 1.0;
then:
- lambda: 'id(constant_weight) = x;'

platform: template
name: Hog Weight2
icon: mdi:scalee
unit_of_measurement: g
accuracy_decimals: 0
lambda: 'return id(weight).state;'
filters:
- lambda: 'return x - id(constant_weight);'
- lambda: 'return x >= 10.0 ? x : 0;'
- delta: 0.5`

**Comment by sbrk-r** [comment]
If you put back the original home assistant button tare mechanism from the demo yaml, or parts of it anyway, you can add this to give a physical button (momentary pushbutton connected from GPIO to ground):

```shell
binary_sensor:
  - platform: gpio
    pin:
      number: <gpio_you_want_to_use>
      inverted: true
      mode:
        input: true
        pullup: true
    name: physical_tare_button
    filters:
      - delayed_off: 10ms
    on_press:
      - lambda: |-
          id(auto_tare_difference) = id(initial_zero) - id(smart_scale_hx711_value_raw).state;
``` 

I use it to zero scale for my dogs.

**Comment by markusressel** [comment]
Sorry @cayote64 I somehow missed your question for all this time.
Thx @sbrk-r for answering! :heart: 

Closing this now since it should be resolved.
