### ISSUE TITLE
Random false readings

### ISSUE THREAD

**Issue by AzonInc** [markusressel/ESPHome-Smart-Scale#2]
Every here and then I get some random false reading. It seems to happen only once to break down to 0-4kg while I'm still on the scale.

Here's an example:

![Screenshot_2023-02-04-11-20-13-02_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/11911587/216761804-5863eb0f-9d85-4f43-9ee4-cb115ef4f80a.jpg)
![Screenshot_2023-02-04-11-26-05-21_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/11911587/216761908-8af23049-c0f6-4490-905f-2d76dd3a30ea.jpg)

I didn't leave the bed all night. However my lights turned on because I use it as a occupancy sensor.

Is there any way to filter these out without impact on report time?

**Comment by markusressel** [comment]
I have seen those spikes as well but I am not entirely sure where they are coming from. We might get less of these outliers if we reduce the polling rate:

https://github.com/markusressel/ESPHome-Smart-Scale/blob/master/esphome_hx711_smart_scale.yaml#L112

The `sliding_window_moving_average` filter was also meant to reduce the severity of those outliers, but the window is probably not big enough to filter out these massive offsets.

**Comment by AzonInc** [comment]
How about the quantile Filter?
I don't know the exact difference but as far as I understand it should prevent spikes like that too.

Do you know the difference between them?

**Comment by markusressel** [comment]
Sounds like a good idea. I will give it a try for the next couple of days.
