### ISSUE TITLE
ESP32 does not work with 5v

### ISSUE THREAD

**Issue by hesspoint** [markusressel/ESPHome-Smart-Scale#29]
Hi,

I connected the hx771 to an ESP32 board using the 5V pin and the GND next to it. The led on the ESP32 blinks quickly and nothing happens. 
I tried changing the GND cable to the other GND pin. Then the led does not blink but the ESP32 does not connect to wifi. 
Then I tried connecting power to the 3,3v pin and that seems to work.

My theory is that on 5v the hx771 pulls too much power that the esp does not have any for the wifi?

Any idea why 5v is not working? Most people and also in this repo it is suggested to use 5v.

**Comment by markusressel** [comment]
According to official specs the HX711 supports 2.6 ~ 5.5V so both should be fine.

**Comment by hesspoint** [comment]
I think not the hx771 is the issue I think that it pulls more power than the esp32 can handle

**Comment by markusressel** [comment]
@hesspoint Anything to report back?

**Comment by hesspoint** [comment]
So far so good on the 3.3v.

**Comment by markusressel** [comment]
Cool! 😎 
I am closing this issue then. Feel free to open another one if necessary.
